In [ ]:
!pwd

/home/piai

In [ ]:
!pip install torch==2.0.1
!pip show torch

Requirement already satisfied: torch==2.0.1 in ./anaconda3/lib/python3.10/site-packages (2.0.1)
Requirement already satisfied: filelock in ./anaconda3/lib/python3.10/site-packages (from torch==2.0.1) (3.13.1)
Requirement already satisfied: typing-extensions in ./anaconda3/lib/python3.10/site-packages (from torch==2.0.1) (4.11.0)
Requirement already satisfied: sympy in ./anaconda3/lib/python3.10/site-packages (from torch==2.0.1) (1.12)
Requirement already satisfied: networkx in ./anaconda3/lib/python3.10/site-packages (from torch==2.0.1) (3.3)
Requirement already satisfied: jinja2 in ./anaconda3/lib/python3.10/site-packages (from torch==2.0.1) (3.1.3)
Requirement already satisfied: nvidia-cuda-nvrtc-cu11==11.7.99 in ./anaconda3/lib/python3.10/site-packages (from torch==2.0.1) (11.7.99)
Requirement already satisfied: nvidia-cuda-runtime-cu11==11.7.99 in ./anaconda3/lib/python3.10/site-packages (from torch==2.0.1) (11.7.99)
Requirement already satisfied: nvidia-cuda-cupti-cu11==11.7.101 in ./anaconda3/lib/python3.10/site-packages (from torch==2.0.1) (11.7.101)
Requirement already satisfied: nvidia-cudnn-cu11==8.5.0.96 in ./anaconda3/lib/python3.10/site-packages (from torch==2.0.1) (8.5.0.96)
Requirement already satisfied: nvidia-cublas-cu11==11.10.3.66 in ./anaconda3/lib/python3.10/site-packages (from torch==2.0.1) (11.10.3.66)
Requirement already satisfied: nvidia-cufft-cu11==10.9.0.58 in ./anaconda3/lib/python3.10/site-packages (from torch==2.0.1) (10.9.0.58)
Requirement already satisfied: nvidia-curand-cu11==10.2.10.91 in ./anaconda3/lib/python3.10/site-packages (from torch==2.0.1) (10.2.10.91)
Requirement already satisfied: nvidia-cusolver-cu11==11.4.0.1 in ./anaconda3/lib/python3.10/site-packages (from torch==2.0.1) (11.4.0.1)
Requirement already satisfied: nvidia-cusparse-cu11==11.7.4.91 in ./anaconda3/lib/python3.10/site-packages (from torch==2.0.1) (11.7.4.91)
Requirement already satisfied: nvidia-nccl-cu11==2.14.3 in ./anaconda3/lib/python3.10/site-packages (from torch==2.0.1) (2.14.3)
Requirement already satisfied: nvidia-nvtx-cu11==11.7.91 in ./anaconda3/lib/python3.10/site-packages (from torch==2.0.1) (11.7.91)
Requirement already satisfied: triton==2.0.0 in ./anaconda3/lib/python3.10/site-packages (from torch==2.0.1) (2.0.0)
Requirement already satisfied: setuptools in ./anaconda3/lib/python3.10/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch==2.0.1) (65.6.3)
Requirement already satisfied: wheel in ./anaconda3/lib/python3.10/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch==2.0.1) (0.38.4)
Requirement already satisfied: cmake in ./anaconda3/lib/python3.10/site-packages (from triton==2.0.0->torch==2.0.1) (3.29.2)
Requirement already satisfied: lit in ./anaconda3/lib/python3.10/site-packages (from triton==2.0.0->torch==2.0.1) (18.1.3)
Requirement already satisfied: MarkupSafe>=2.0 in ./anaconda3/lib/python3.10/site-packages (from jinja2->torch==2.0.1) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in ./anaconda3/lib/python3.10/site-packages (from sympy->torch==2.0.1) (1.3.0)
Name: torch
Version: 2.0.1
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /home/piai/anaconda3/lib/python3.10/site-packages
Requires: filelock, jinja2, networkx, nvidia-cublas-cu11, nvidia-cuda-cupti-cu11, nvidia-cuda-nvrtc-cu11, nvidia-cuda-runtime-cu11, nvidia-cudnn-cu11, nvidia-cufft-cu11, nvidia-curand-cu11, nvidia-cusolver-cu11, nvidia-cusparse-cu11, nvidia-nccl-cu11, nvidia-nvtx-cu11, sympy, triton, typing-extensions
Required-by: thop, torchvision, triton, ultralytics

In [ ]:
!pip install -r requirements.txt

ERROR: Could not open requirements file: [Errno 2] 그런 파일이나 디렉터리가 없습니다: 'requirements.txt'

In [ ]:
!pip show torch

Name: torch
Version: 2.0.1
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /home/piai/anaconda3/lib/python3.10/site-packages
Requires: filelock, jinja2, networkx, nvidia-cublas-cu11, nvidia-cuda-cupti-cu11, nvidia-cuda-nvrtc-cu11, nvidia-cuda-runtime-cu11, nvidia-cudnn-cu11, nvidia-cufft-cu11, nvidia-curand-cu11, nvidia-cusolver-cu11, nvidia-cusparse-cu11, nvidia-nccl-cu11, nvidia-nvtx-cu11, sympy, triton, typing-extensions
Required-by: thop, torchvision, triton, ultralytics

In [ ]:
# # yolov8 프로젝트 다운
# !git clone https://github.com/ultralytics/ultralytics.git

In [ ]:
# !pip install ultralytics

In [ ]:
!pwd

/home/piai

In [ ]:
cd /home/piai/project_yolo/ultralytics

/home/piai/project_yolo/ultralytics

In [ ]:
# !pip install -r requirements.txt

In [ ]:
# yolov8n.pt 파일이 생성 확인
!yolo predict

WARNING ⚠️ Ultralytics settings reset to default values. This may be due to a possible problem with your settings or a recent ultralytics package update.
View settings with 'yolo settings' or at '/home/piai/.config/Ultralytics/settings.yaml'
Update settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'.
Traceback (most recent call last):
  File "/home/piai/yes/bin/yolo", line 5, in <module>
    from ultralytics.cfg import entrypoint
  File "/home/piai/yes/lib/python3.10/site-packages/ultralytics/__init__.py", line 5, in <module>
    from ultralytics.models import RTDETR, SAM, YOLO
  File "/home/piai/yes/lib/python3.10/site-packages/ultralytics/models/__init__.py", line 3, in <module>
    from .rtdetr import RTDETR
  File "/home/piai/yes/lib/python3.10/site-packages/ultralytics/models/rtdetr/__init__.py", line 3, in <module>
    from .model import RTDETR
  File "/home/piai/yes/lib/python3.10/site-packages/ultralytics/models/rtdetr/model.py", line 3, in <module>
    from ultralytics.engine.model import Model
  File "/home/piai/yes/lib/python3.10/site-packages/ultralytics/engine/model.py", line 9, in <module>
    from ultralytics.hub.utils import HUB_WEB_ROOT
  File "/home/piai/yes/lib/python3.10/site-packages/ultralytics/hub/__init__.py", line 5, in <module>
    from ultralytics.data.utils import HUBDatasetStats
  File "/home/piai/yes/lib/python3.10/site-packages/ultralytics/data/__init__.py", line 4, in <module>
    from .build import build_dataloader, build_yolo_dataset, load_inference_source
  File "/home/piai/yes/lib/python3.10/site-packages/ultralytics/data/build.py", line 18, in <module>
    from .dataset import YOLODataset
  File "/home/piai/yes/lib/python3.10/site-packages/ultralytics/data/dataset.py", line 195, in <module>
    class ClassificationDataset(torchvision.datasets.ImageFolder):
AttributeError: module 'torchvision' has no attribute 'datasets'

In [ ]:
# # roboflow 헬멧 데이터셋 다운
# !curl -L "https://universe.roboflow.com/ds/qgR7XKGaKG?key=tl15904Y5z" &gt; roboflow.zip; unzip roboflow.zip; rm roboflow.zip

In [ ]:
# # # roboflow 헬멧 데이터셋 다운 - api키로 다운
# # api_key 본인 api키 넣어주세요 (내정보 - private api key)
!pip install roboflow
from roboflow import Roboflow
rf = Roboflow(api_key="")
project = rf.workspace("").project("")
version = project.version()
dataset = version.download("")

Requirement already satisfied: roboflow in /home/piai/anaconda3/lib/python3.10/site-packages (1.1.27)
Requirement already satisfied: certifi==2023.7.22 in /home/piai/anaconda3/lib/python3.10/site-packages (from roboflow) (2023.7.22)
Requirement already satisfied: chardet==4.0.0 in /home/piai/anaconda3/lib/python3.10/site-packages (from roboflow) (4.0.0)
Requirement already satisfied: cycler==0.10.0 in /home/piai/anaconda3/lib/python3.10/site-packages (from roboflow) (0.10.0)
Requirement already satisfied: idna==2.10 in /home/piai/anaconda3/lib/python3.10/site-packages (from roboflow) (2.10)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/piai/anaconda3/lib/python3.10/site-packages (from roboflow) (1.4.5)
Requirement already satisfied: matplotlib in /home/piai/anaconda3/lib/python3.10/site-packages (from roboflow) (3.8.4)
Requirement already satisfied: numpy>=1.18.5 in /home/piai/anaconda3/lib/python3.10/site-packages (from roboflow) (1.26.4)
Requirement already satisfied: opencv-python-headless==4.8.0.74 in /home/piai/anaconda3/lib/python3.10/site-packages (from roboflow) (4.8.0.74)
Requirement already satisfied: Pillow>=7.1.2 in /home/piai/anaconda3/lib/python3.10/site-packages (from roboflow) (10.2.0)
Requirement already satisfied: python-dateutil in /home/piai/anaconda3/lib/python3.10/site-packages (from roboflow) (2.8.2)
Requirement already satisfied: python-dotenv in /home/piai/anaconda3/lib/python3.10/site-packages (from roboflow) (1.0.1)
Requirement already satisfied: requests in /home/piai/anaconda3/lib/python3.10/site-packages (from roboflow) (2.31.0)
Requirement already satisfied: six in /home/piai/anaconda3/lib/python3.10/site-packages (from roboflow) (1.16.0)
Requirement already satisfied: urllib3>=1.26.6 in /home/piai/anaconda3/lib/python3.10/site-packages (from roboflow) (2.1.0)
Requirement already satisfied: tqdm>=4.41.0 in /home/piai/anaconda3/lib/python3.10/site-packages (from roboflow) (4.65.0)
Requirement already satisfied: PyYAML>=5.3.1 in /home/piai/anaconda3/lib/python3.10/site-packages (from roboflow) (6.0.1)
Requirement already satisfied: requests-toolbelt in /home/piai/anaconda3/lib/python3.10/site-packages (from roboflow) (1.0.0)
Requirement already satisfied: python-magic in /home/piai/anaconda3/lib/python3.10/site-packages (from roboflow) (0.4.27)
Requirement already satisfied: contourpy>=1.0.1 in /home/piai/anaconda3/lib/python3.10/site-packages (from matplotlib->roboflow) (1.2.1)
Requirement already satisfied: fonttools>=4.22.0 in /home/piai/anaconda3/lib/python3.10/site-packages (from matplotlib->roboflow) (4.51.0)
Requirement already satisfied: packaging>=20.0 in /home/piai/anaconda3/lib/python3.10/site-packages (from matplotlib->roboflow) (23.2)
Requirement already satisfied: pyparsing>=2.3.1 in /home/piai/anaconda3/lib/python3.10/site-packages (from matplotlib->roboflow) (3.1.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/piai/anaconda3/lib/python3.10/site-packages (from requests->roboflow) (2.0.4)
loading Roboflow workspace...
loading Roboflow project...
Dependency ultralytics==8.0.196 is required but found version=8.1.45, to fix: `pip install ultralytics==8.0.196`

Downloading Dataset Version Zip in poskick_helmet-7 to yolov8:: 100%|█| 61130/61

Extracting Dataset Version Zip to poskick_helmet-7 in yolov8:: 100%|█| 3844/3844

In [ ]:
!pip install ultralytics==8.0.196

Requirement already satisfied: ultralytics==8.0.196 in /home/piai/anaconda3/lib/python3.10/site-packages (8.0.196)
Requirement already satisfied: matplotlib>=3.3.0 in /home/piai/anaconda3/lib/python3.10/site-packages (from ultralytics==8.0.196) (3.8.4)
Requirement already satisfied: numpy>=1.22.2 in /home/piai/anaconda3/lib/python3.10/site-packages (from ultralytics==8.0.196) (1.26.4)
Requirement already satisfied: opencv-python>=4.6.0 in /home/piai/anaconda3/lib/python3.10/site-packages (from ultralytics==8.0.196) (4.9.0.80)
Requirement already satisfied: pillow>=7.1.2 in /home/piai/anaconda3/lib/python3.10/site-packages (from ultralytics==8.0.196) (10.2.0)
Requirement already satisfied: pyyaml>=5.3.1 in /home/piai/anaconda3/lib/python3.10/site-packages (from ultralytics==8.0.196) (6.0.1)
Requirement already satisfied: requests>=2.23.0 in /home/piai/anaconda3/lib/python3.10/site-packages (from ultralytics==8.0.196) (2.31.0)
Requirement already satisfied: scipy>=1.4.1 in /home/piai/anaconda3/lib/python3.10/site-packages (from ultralytics==8.0.196) (1.13.0)
Requirement already satisfied: torch>=1.8.0 in /home/piai/anaconda3/lib/python3.10/site-packages (from ultralytics==8.0.196) (2.0.1)
Requirement already satisfied: torchvision>=0.9.0 in /home/piai/anaconda3/lib/python3.10/site-packages (from ultralytics==8.0.196) (0.15.2)
Requirement already satisfied: tqdm>=4.64.0 in /home/piai/anaconda3/lib/python3.10/site-packages (from ultralytics==8.0.196) (4.65.0)
Requirement already satisfied: pandas>=1.1.4 in /home/piai/anaconda3/lib/python3.10/site-packages (from ultralytics==8.0.196) (2.2.2)
Requirement already satisfied: seaborn>=0.11.0 in /home/piai/anaconda3/lib/python3.10/site-packages (from ultralytics==8.0.196) (0.13.2)
Requirement already satisfied: psutil in /home/piai/anaconda3/lib/python3.10/site-packages (from ultralytics==8.0.196) (5.9.0)
Requirement already satisfied: py-cpuinfo in /home/piai/anaconda3/lib/python3.10/site-packages (from ultralytics==8.0.196) (9.0.0)
Requirement already satisfied: thop>=0.1.1 in /home/piai/anaconda3/lib/python3.10/site-packages (from ultralytics==8.0.196) (0.1.1.post2209072238)
Requirement already satisfied: contourpy>=1.0.1 in /home/piai/anaconda3/lib/python3.10/site-packages (from matplotlib>=3.3.0->ultralytics==8.0.196) (1.2.1)
Requirement already satisfied: cycler>=0.10 in /home/piai/anaconda3/lib/python3.10/site-packages (from matplotlib>=3.3.0->ultralytics==8.0.196) (0.10.0)
Requirement already satisfied: fonttools>=4.22.0 in /home/piai/anaconda3/lib/python3.10/site-packages (from matplotlib>=3.3.0->ultralytics==8.0.196) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/piai/anaconda3/lib/python3.10/site-packages (from matplotlib>=3.3.0->ultralytics==8.0.196) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /home/piai/anaconda3/lib/python3.10/site-packages (from matplotlib>=3.3.0->ultralytics==8.0.196) (23.2)
Requirement already satisfied: pyparsing>=2.3.1 in /home/piai/anaconda3/lib/python3.10/site-packages (from matplotlib>=3.3.0->ultralytics==8.0.196) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in /home/piai/anaconda3/lib/python3.10/site-packages (from matplotlib>=3.3.0->ultralytics==8.0.196) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /home/piai/anaconda3/lib/python3.10/site-packages (from pandas>=1.1.4->ultralytics==8.0.196) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.7 in /home/piai/anaconda3/lib/python3.10/site-packages (from pandas>=1.1.4->ultralytics==8.0.196) (2024.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/piai/anaconda3/lib/python3.10/site-packages (from requests>=2.23.0->ultralytics==8.0.196) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /home/piai/anaconda3/lib/python3.10/site-packages (from requests>=2.23.0->ultralytics==8.0.196) (2.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/piai/anaconda3/lib/python3.10/site-packages (from requests>=2.23.0->ultralytics==8.0.196) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/piai/anaconda3/lib/python3.10/site-packages (from requests>=2.23.0->ultralytics==8.0.196) (2023.7.22)
Requirement already satisfied: filelock in /home/piai/anaconda3/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics==8.0.196) (3.13.1)
Requirement already satisfied: typing-extensions in /home/piai/anaconda3/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics==8.0.196) (4.11.0)
Requirement already satisfied: sympy in /home/piai/anaconda3/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics==8.0.196) (1.12)
Requirement already satisfied: networkx in /home/piai/anaconda3/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics==8.0.196) (3.3)
Requirement already satisfied: jinja2 in /home/piai/anaconda3/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics==8.0.196) (3.1.3)
Requirement already satisfied: nvidia-cuda-nvrtc-cu11==11.7.99 in /home/piai/anaconda3/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics==8.0.196) (11.7.99)
Requirement already satisfied: nvidia-cuda-runtime-cu11==11.7.99 in /home/piai/anaconda3/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics==8.0.196) (11.7.99)
Requirement already satisfied: nvidia-cuda-cupti-cu11==11.7.101 in /home/piai/anaconda3/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics==8.0.196) (11.7.101)
Requirement already satisfied: nvidia-cudnn-cu11==8.5.0.96 in /home/piai/anaconda3/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics==8.0.196) (8.5.0.96)
Requirement already satisfied: nvidia-cublas-cu11==11.10.3.66 in /home/piai/anaconda3/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics==8.0.196) (11.10.3.66)
Requirement already satisfied: nvidia-cufft-cu11==10.9.0.58 in /home/piai/anaconda3/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics==8.0.196) (10.9.0.58)
Requirement already satisfied: nvidia-curand-cu11==10.2.10.91 in /home/piai/anaconda3/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics==8.0.196) (10.2.10.91)
Requirement already satisfied: nvidia-cusolver-cu11==11.4.0.1 in /home/piai/anaconda3/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics==8.0.196) (11.4.0.1)
Requirement already satisfied: nvidia-cusparse-cu11==11.7.4.91 in /home/piai/anaconda3/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics==8.0.196) (11.7.4.91)
Requirement already satisfied: nvidia-nccl-cu11==2.14.3 in /home/piai/anaconda3/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics==8.0.196) (2.14.3)
Requirement already satisfied: nvidia-nvtx-cu11==11.7.91 in /home/piai/anaconda3/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics==8.0.196) (11.7.91)
Requirement already satisfied: triton==2.0.0 in /home/piai/anaconda3/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics==8.0.196) (2.0.0)
Requirement already satisfied: setuptools in /home/piai/anaconda3/lib/python3.10/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch>=1.8.0->ultralytics==8.0.196) (65.6.3)
Requirement already satisfied: wheel in /home/piai/anaconda3/lib/python3.10/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch>=1.8.0->ultralytics==8.0.196) (0.38.4)
Requirement already satisfied: cmake in /home/piai/anaconda3/lib/python3.10/site-packages (from triton==2.0.0->torch>=1.8.0->ultralytics==8.0.196) (3.29.2)
Requirement already satisfied: lit in /home/piai/anaconda3/lib/python3.10/site-packages (from triton==2.0.0->torch>=1.8.0->ultralytics==8.0.196) (18.1.3)
Requirement already satisfied: six in /home/piai/anaconda3/lib/python3.10/site-packages (from cycler>=0.10->matplotlib>=3.3.0->ultralytics==8.0.196) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/piai/anaconda3/lib/python3.10/site-packages (from jinja2->torch>=1.8.0->ultralytics==8.0.196) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in /home/piai/anaconda3/lib/python3.10/site-packages (from sympy->torch>=1.8.0->ultralytics==8.0.196) (1.3.0)

In [ ]:
# train, test 폴더 생성 확인
!pwd
from glob import glob

train_img_list = glob('/home/piai/project_yolo/ultralytics/poskick_helmet_7/train/images/*.jpg')
train_txt_list = glob('/home/piai/project_yolo/ultralytics/poskick_helmet_7/train/labels/*.txt')
val_img_list = glob('/home/piai/project_yolo/ultralytics/poskick_helmet_7/valid/images/*.jpg')
val_txt_list = glob('/home/piai/project_yolo/ultralytics/poskick_helmet_7/valid/labels/*.txt')
test_img_list = glob('/home/piai/project_yolo/ultralytics/poskick_helmet_7/test/images/*.jpg')
test_txt_list = glob('/home/piai/project_yolo/ultralytics/poskick_helmet_7/test/labels/*.txt')

print(len(train_img_list), len(train_txt_list))
print(len(val_img_list), len(val_txt_list))
print(len(test_img_list), len(test_txt_list))

/home/piai/project_yolo/ultralytics
1340 1340
385 385
191 191

In [ ]:
# # train데이터와 val 데이터 나누기
# from sklearn.model_selection import train_test_split

# train_img_list, val_img_list = train_test_split(train_img_list, test_size=0.2, random_state=2000)

# print(len(train_img_list), len(val_img_list))

In [ ]:
# 파일 쓰기
with open('/home/piai/project_yolo/ultralytics/poskick_helmet_7/train.txt', 'w') as f:
    f.write('\n'.join(train_img_list) + '\n')

with open('/home/piai/project_yolo/ultralytics/poskick_helmet_7/val.txt', 'w') as f:
    f.write('\n'.join(val_img_list) + '\n')

with open('/home/piai/project_yolo/ultralytics/poskick_helmet_7/test.txt', 'w') as f:
    f.write('\n'.join(test_img_list) + '\n')

In [ ]:
!pip install pyyaml

Requirement already satisfied: pyyaml in /home/piai/anaconda3/lib/python3.10/site-packages (6.0.1)

In [ ]:
# yaml 파일 수정
import yaml

with open('/home/piai/project_yolo/ultralytics/poskick_helmet_7/data.yaml', 'r') as f:
    data = yaml.full_load(f) #yaml load -> yaml full load

print(data)

data['train'] = '/home/piai/project_yolo/ultralytics/poskick_helmet_7/train.txt'
data['val'] = '/home/piai/project_yolo/ultralytics/poskick_helmet_7/val.txt'
data['test'] = '/home/piai/project_yolo/ultralytics/poskick_helmet_7/test.txt'

with open('/home/piai/project_yolo/ultralytics/poskick_helmet_7/data.yaml', 'w') as f:
    yaml.dump(data, f)

{'names': ['helmet'], 'nc': 1, 'roboflow': {'license': 'CC BY 4.0', 'project': 'poskick_helmet', 'url': 'https://universe.roboflow.com/krh/poskick_helmet/dataset/7', 'version': 7, 'workspace': 'krh'}, 'test': '/home/piai/project_yolo/ultralytics/poskick_helmet_7/test.txt', 'train': '/home/piai/project_yolo/ultralytics/poskick_helmet_7/train.txt', 'val': '/home/piai/project_yolo/ultralytics/poskick_helmet_7/val.txt'}

In [ ]:
# nvcc --version

In [ ]:
#!pip install torch==2.2.1

In [ ]:
!pip show torch

Name: torch
Version: 2.0.1
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /home/piai/yes/lib/python3.10/site-packages
Requires: filelock, jinja2, networkx, nvidia-cublas-cu11, nvidia-cuda-cupti-cu11, nvidia-cuda-nvrtc-cu11, nvidia-cuda-runtime-cu11, nvidia-cudnn-cu11, nvidia-cufft-cu11, nvidia-curand-cu11, nvidia-cusolver-cu11, nvidia-cusparse-cu11, nvidia-nccl-cu11, nvidia-nvtx-cu11, sympy, triton, typing-extensions
Required-by: thop, torchaudio, torchvision, triton, ultralytics

In [ ]:
# !pip install --upgrade tensorflow==2.2
# !pip install pytorch-cuda==11.8

In [ ]:
# import os
# os.environ['CUDA_LAUNCH_BLOCKING'] = '1'
# os.environ["CUDA_VISIBLE_DEVICES"] = "0"
# os.environ["TORCH_USE_CUDA_DSA"] = '1'

In [ ]:
!pip install torchvision==0.15.2

Collecting torchvision==0.15.2
  Downloading torchvision-0.15.2-cp310-cp310-manylinux1_x86_64.whl (6.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.0/6.0 MB 14.5 MB/s eta 0:00:00m eta 0:00:01[36m0:00:01
Requirement already satisfied: torch==2.0.1 in /home/piai/yes/lib/python3.10/site-packages (from torchvision==0.15.2) (2.0.1)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /home/piai/yes/lib/python3.10/site-packages (from torchvision==0.15.2) (10.2.0)
Requirement already satisfied: requests in /home/piai/yes/lib/python3.10/site-packages (from torchvision==0.15.2) (2.31.0)
Requirement already satisfied: numpy in /home/piai/yes/lib/python3.10/site-packages (from torchvision==0.15.2) (1.26.4)
Requirement already satisfied: sympy in /home/piai/yes/lib/python3.10/site-packages (from torch==2.0.1->torchvision==0.15.2) (1.12)
Requirement already satisfied: typing-extensions in /home/piai/yes/lib/python3.10/site-packages (from torch==2.0.1->torchvision==0.15.2) (4.9.0)
Requirement already satisfied: nvidia-cufft-cu11==10.9.0.58 in /home/piai/yes/lib/python3.10/site-packages (from torch==2.0.1->torchvision==0.15.2) (10.9.0.58)
Requirement already satisfied: networkx in /home/piai/yes/lib/python3.10/site-packages (from torch==2.0.1->torchvision==0.15.2) (3.1)
Requirement already satisfied: nvidia-cuda-runtime-cu11==11.7.99 in /home/piai/yes/lib/python3.10/site-packages (from torch==2.0.1->torchvision==0.15.2) (11.7.99)
Requirement already satisfied: nvidia-nccl-cu11==2.14.3 in /home/piai/yes/lib/python3.10/site-packages (from torch==2.0.1->torchvision==0.15.2) (2.14.3)
Requirement already satisfied: jinja2 in /home/piai/yes/lib/python3.10/site-packages (from torch==2.0.1->torchvision==0.15.2) (3.1.3)
Requirement already satisfied: nvidia-cuda-nvrtc-cu11==11.7.99 in /home/piai/yes/lib/python3.10/site-packages (from torch==2.0.1->torchvision==0.15.2) (11.7.99)
Requirement already satisfied: nvidia-cuda-cupti-cu11==11.7.101 in /home/piai/yes/lib/python3.10/site-packages (from torch==2.0.1->torchvision==0.15.2) (11.7.101)
Requirement already satisfied: nvidia-nvtx-cu11==11.7.91 in /home/piai/yes/lib/python3.10/site-packages (from torch==2.0.1->torchvision==0.15.2) (11.7.91)
Requirement already satisfied: triton==2.0.0 in /home/piai/yes/lib/python3.10/site-packages (from torch==2.0.1->torchvision==0.15.2) (2.0.0)
Requirement already satisfied: nvidia-cudnn-cu11==8.5.0.96 in /home/piai/yes/lib/python3.10/site-packages (from torch==2.0.1->torchvision==0.15.2) (8.5.0.96)
Requirement already satisfied: nvidia-curand-cu11==10.2.10.91 in /home/piai/yes/lib/python3.10/site-packages (from torch==2.0.1->torchvision==0.15.2) (10.2.10.91)
Requirement already satisfied: nvidia-cublas-cu11==11.10.3.66 in /home/piai/yes/lib/python3.10/site-packages (from torch==2.0.1->torchvision==0.15.2) (11.10.3.66)
Requirement already satisfied: nvidia-cusolver-cu11==11.4.0.1 in /home/piai/yes/lib/python3.10/site-packages (from torch==2.0.1->torchvision==0.15.2) (11.4.0.1)
Requirement already satisfied: nvidia-cusparse-cu11==11.7.4.91 in /home/piai/yes/lib/python3.10/site-packages (from torch==2.0.1->torchvision==0.15.2) (11.7.4.91)
Requirement already satisfied: filelock in /home/piai/yes/lib/python3.10/site-packages (from torch==2.0.1->torchvision==0.15.2) (3.13.1)
Requirement already satisfied: wheel in /home/piai/yes/lib/python3.10/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch==2.0.1->torchvision==0.15.2) (0.38.4)
Requirement already satisfied: setuptools in /home/piai/yes/lib/python3.10/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch==2.0.1->torchvision==0.15.2) (65.6.3)
Requirement already satisfied: cmake in /home/piai/yes/lib/python3.10/site-packages (from triton==2.0.0->torch==2.0.1->torchvision==0.15.2) (3.29.0.1)
Requirement already satisfied: lit in /home/piai/yes/lib/python3.10/site-packages (from triton==2.0.0->torch==2.0.1->torchvision==0.15.2) (18.1.2)
Requirement already satisfied: idna<4,>=2.5 in /home/piai/yes/lib/python3.10/site-packages (from requests->torchvision==0.15.2) (2.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/piai/yes/lib/python3.10/site-packages (from requests->torchvision==0.15.2) (2.2.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/piai/yes/lib/python3.10/site-packages (from requests->torchvision==0.15.2) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /home/piai/yes/lib/python3.10/site-packages (from requests->torchvision==0.15.2) (2023.7.22)
Requirement already satisfied: MarkupSafe>=2.0 in /home/piai/yes/lib/python3.10/site-packages (from jinja2->torch==2.0.1->torchvision==0.15.2) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in /home/piai/yes/lib/python3.10/site-packages (from sympy->torch==2.0.1->torchvision==0.15.2) (1.3.0)
Installing collected packages: torchvision
  Attempting uninstall: torchvision
    Found existing installation: torchvision 0.15.0
    Uninstalling torchvision-0.15.0:
      Successfully uninstalled torchvision-0.15.0
Successfully installed torchvision-0.15.2

In [ ]:
!pwd
!yolo detect train data=/home/piai/project_yolo/ultralytics/poskick_helmet_7/data.yaml model=yolov8n.pt epochs=120 imgsz=640 lr0=0.01 device=0

/home/piai/project_yolo/ultralytics
New https://pypi.org/project/ultralytics/8.2.2 available 😃 Update with 'pip install -U ultralytics'
Ultralytics YOLOv8.0.196 🚀 Python-3.10.14 torch-2.0.1+cu117 CUDA:0 (NVIDIA GeForce RTX 2080, 7979MiB)
engine/trainer: task=detect, mode=train, model=yolov8n.pt, data=/home/piai/project_yolo/ultralytics/poskick_helmet_7/data.yaml, epochs=120, patience=50, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=0, workers=8, project=None, name=None, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, stream_buffer=False, line_width=None, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, tracker=botsort.yaml, save_dir=runs/detect/train25
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    751507  ultralytics.nn.modules.head.Detect           [1, [64, 128, 256]]
Model summary: 225 layers, 3011043 parameters, 3011027 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
AMP: checks passed ✅
train: Scanning /home/piai/project_yolo/ultralytics/poskick_helmet_7/train/label
train: New cache created: /home/piai/project_yolo/ultralytics/poskick_helmet_7/train/labels.cache
val: Scanning /home/piai/project_yolo/ultralytics/poskick_helmet_7/valid/labels.
val: New cache created: /home/piai/project_yolo/ultralytics/poskick_helmet_7/valid/labels.cache
Plotting labels to runs/detect/train25/labels.jpg...
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.002, momentum=0.9) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to runs/detect/train25
Starting training for 120 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      1/120      2.33G        0.7       1.58      1.223         36        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m
                   all        385        451      0.829      0.736      0.786      0.557

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      2/120      2.34G     0.7604      1.184       1.25         41        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m
                   all        385        451       0.52      0.503      0.488       0.33

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      3/120      2.34G     0.7772      1.059      1.257         35        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m
                   all        385        451      0.276       0.57      0.248      0.159

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      4/120      2.36G     0.7729     0.9582      1.252         35        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m
                   all        385        451      0.717      0.645      0.712      0.493

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      5/120      2.34G     0.7407     0.9141      1.228         38        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m
                   all        385        451      0.839      0.772      0.858      0.643

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      6/120      2.34G     0.6959     0.8165      1.207         30        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m
                   all        385        451      0.801      0.703      0.776      0.522

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      7/120      2.36G     0.6633     0.7718      1.179         31        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m
                   all        385        451      0.863      0.785      0.874      0.697

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      8/120      2.33G     0.6345     0.7276      1.156         31        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m
                   all        385        451       0.83      0.705      0.822       0.64

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      9/120      2.33G       0.66     0.7493      1.177         36        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m
                   all        385        451      0.818      0.845      0.903       0.73

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     10/120      2.33G     0.6521     0.7399      1.171         35        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m
                   all        385        451       0.86      0.845      0.905      0.728

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     11/120      2.33G     0.6299     0.6985      1.147         30        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m
                   all        385        451      0.813       0.82       0.88      0.701

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     12/120      2.33G     0.5985     0.6738      1.131         31        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m
                   all        385        451      0.868      0.805      0.891      0.676

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     13/120      2.36G     0.6093     0.6805      1.136         35        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m
                   all        385        451      0.855      0.813      0.893      0.713

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     14/120      2.33G     0.5989     0.6506       1.13         29        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m
                   all        385        451      0.853      0.833      0.899      0.749

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     15/120      2.33G     0.5831     0.6413      1.106         29        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m
                   all        385        451      0.892      0.863      0.923      0.753

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     16/120      2.33G     0.5595     0.6102      1.107         33        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m
                   all        385        451      0.848      0.809      0.889      0.689

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     17/120      2.35G     0.5639     0.6205      1.106         37        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m
                   all        385        451      0.822      0.801      0.879      0.709

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     18/120      2.33G     0.5527     0.6025      1.104         42        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m
                   all        385        451      0.873      0.842      0.911      0.729

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     19/120      2.35G     0.5684     0.6135       1.11         27        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m
                   all        385        451      0.873      0.809      0.906      0.732

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     20/120      2.33G     0.5381     0.5597      1.096         30        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m
                   all        385        451      0.918      0.889      0.939      0.781

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     21/120      2.33G     0.5501      0.583      1.096         32        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m
                   all        385        451      0.885        0.8      0.881      0.696

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     22/120      2.33G     0.5505     0.5774      1.101         32        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m
                   all        385        451      0.889      0.819        0.9      0.703

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     23/120      2.33G     0.5278     0.5518      1.092         32        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m
                   all        385        451      0.906      0.894      0.939      0.788

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     24/120      2.33G     0.5287     0.5638      1.098         28        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m
                   all        385        451      0.914      0.869      0.945      0.778

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     25/120      2.38G     0.5159     0.5472      1.077         28        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m
                   all        385        451      0.904      0.851      0.933      0.784

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     26/120      2.33G     0.5277     0.5442      1.082         22        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m
                   all        385        451      0.887      0.871      0.936      0.772

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     27/120      2.33G     0.5272     0.5295      1.082         37        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m
                   all        385        451      0.872      0.876      0.901       0.72

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     28/120      2.33G     0.5163      0.518       1.07         40        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m
                   all        385        451      0.936      0.903      0.961      0.813

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     29/120      2.33G     0.5066     0.4978      1.078         32        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m
                   all        385        451      0.958      0.882      0.969      0.813

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     30/120      2.33G     0.4974     0.5053      1.072         33        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m
                   all        385        451      0.906      0.898      0.959      0.803

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     31/120      2.33G     0.4842     0.4946      1.056         42        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m
                   all        385        451      0.873      0.927      0.942      0.794

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     32/120      2.35G     0.5245     0.5149      1.089         40        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m
                   all        385        451      0.885      0.887      0.937      0.796

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     33/120      2.33G     0.4713     0.4704      1.052         30        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m
                   all        385        451       0.93      0.911      0.956      0.798

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     34/120      2.33G     0.4822     0.4821      1.055         35        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m
                   all        385        451      0.923      0.905      0.957      0.814

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     35/120      2.35G     0.4815     0.4682      1.057         26        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m
                   all        385        451      0.943      0.907      0.959       0.81

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     36/120      2.33G     0.4863     0.4684       1.05         30        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m
                   all        385        451      0.954      0.909      0.967      0.817

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     37/120      2.33G     0.4715     0.4674       1.05         29        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m
                   all        385        451      0.932      0.911      0.965      0.807

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     38/120      2.33G     0.4774     0.4729      1.057         30        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m
                   all        385        451      0.918      0.907       0.95        0.8

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     39/120      2.33G     0.4865     0.4768      1.055         38        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m
                   all        385        451       0.93      0.887      0.942      0.788

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     40/120      2.33G     0.4775     0.4575      1.044         26        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m
                   all        385        451      0.949      0.902      0.959      0.803

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     41/120      2.36G     0.4989     0.4635      1.062         34        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m
                   all        385        451      0.916      0.896      0.945      0.795

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     42/120      2.35G     0.4283     0.4143      1.017         30        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m
                   all        385        451      0.906        0.9       0.95      0.813

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     43/120      2.37G       0.45     0.4202      1.033         43        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m
                   all        385        451       0.92      0.938      0.974      0.832

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     44/120      2.33G     0.4785     0.4414      1.042         35        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m
                   all        385        451      0.919      0.934      0.973      0.825

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
     45/120      2.33G     0.4572     0.4369       1.03         29        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m
                   all        385        451      0.941      0.924      0.972      0.819


### 경량화 전 지표 측정

In [ ]:
# 모델의 총 파라미터 수 계산
total_params = sum(p.numel() for p in model.parameters())

# 모델의 학습 가능한 총 파라미터 수 계산
trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)

print(f"Total Parameters: {total_params}")
print(f"Trainable Parameters: {trainable_params}")

Total Parameters: 3151904
Trainable Parameters: 0

In [ ]:
from ultralytics.utils.benchmarks import benchmark

# Benchmark on GPU
benchmark(model='/home/piai/project_yolo/ultralytics/runs/detect/train25/weights/helmet_final.pt', data='/home/piai/project_yolo/ultralytics/poskick_helmet_7/data.yaml', imgsz=640, half=False, device=0)

Setup complete ✅ (8 CPUs, 62.5 GB RAM, 133.8/233.2 GB disk)

Benchmarks complete for helmet_final.pt on /home/piai/project_yolo/ultralytics/poskick_helmet_7/data.yaml at imgsz=640 (253.11s)
                   Format Status❔  Size (MB)  metrics/mAP50-95(B)  Inference time (ms/im)
0                 PyTorch       ✅        6.0               0.8769                   12.23
1             TorchScript       ✅       11.9               0.8746                    4.70
2                    ONNX       ✅       11.7               0.8746                    6.18
3                OpenVINO       ❌        0.0                  NaN                     NaN
4                TensorRT       ❎       14.5                  NaN                     NaN
5                  CoreML       ❌        0.0                  NaN                     NaN
6   TensorFlow SavedModel       ❌        0.0                  NaN                     NaN
7     TensorFlow GraphDef       ❌        0.0                  NaN                     NaN
8         TensorFlow Lite       ❌        0.0                  NaN                     NaN
9     TensorFlow Edge TPU       ❌        0.0                  NaN                     NaN
10          TensorFlow.js       ❌        0.0                  NaN                     NaN
11           PaddlePaddle       ✅       23.3               0.8746                  274.63
12                   NCNN       ✅       11.6               0.8746                   81.48

                   Format Status❔  Size (MB)  metrics/mAP50-95(B)  Inference time (ms/im)
0                 PyTorch       ✅        6.0               0.8769                   12.23
1             TorchScript       ✅       11.9               0.8746                    4.70
2                    ONNX       ✅       11.7               0.8746                    6.18
3                OpenVINO       ❌        0.0                  NaN                     NaN
4                TensorRT       ❎       14.5                  NaN                     NaN
5                  CoreML       ❌        0.0                  NaN                     NaN
6   TensorFlow SavedModel       ❌        0.0                  NaN                     NaN
7     TensorFlow GraphDef       ❌        0.0                  NaN                     NaN
8         TensorFlow Lite       ❌        0.0                  NaN                     NaN
9     TensorFlow Edge TPU       ❌        0.0                  NaN                     NaN
10          TensorFlow.js       ❌        0.0                  NaN                     NaN
11           PaddlePaddle       ✅       23.3               0.8746                  274.63
12                   NCNN       ✅       11.6               0.8746                   81.48

In [ ]:
import torch
import cv2
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
import time
from glob import glob

class HelmetDataset(Dataset):
    def __init__(self, img_list, txt_list, transform=None):
        self.img_list = img_list
        self.txt_list = txt_list
        self.transform = transform

    def __len__(self):
        return len(self.img_list)

    def __getitem__(self, idx):
        img_path = self.img_list[idx]
        img = cv2.imread(img_path)
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

        if self.transform:
            img = self.transform(img)

        return img

# Transforms
transform = transforms.Compose([
    transforms.ToPILImage(),  # OpenCV로 로드된 이미지를 PIL 이미지로 변환
    transforms.Resize((256, 256)),  # 이미지 크기 조정
    transforms.ToTensor(),  # 텐서로 변환
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])  # 정규화
])

# 데이터셋 및 데이터 로더 설정
# test_img_list = glob('/home/piai/project_yolo/ultralytics/poskick_helmet_7/test/images/*.jpg')
test_dataset = HelmetDataset(test_img_list, [], transform=transform)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

# # 모델 정의
model = YOLO("/home/piai/project_yolo/ultralytics/runs/detect/train25/weights/helmet_final.pt")
# model = model.to('cuda' if torch.cuda.is_available() else 'cpu')

# FPS 측정
start_time = time.time()
num_frames = 0

model.eval()
with torch.no_grad():
    for images in test_loader:
        images = images.to('cuda' if torch.cuda.is_available() else 'cpu')
        start = time.time()
        _ = model(images)  # 모델 예측 (실제 모델 사용시 변경)
        end = time.time()
        num_frames += images.size(0)
        print(f"Processed {images.size(0)} frames in {end - start:.3f} seconds.")

total_time = time.time() - start_time
fps = num_frames / total_time
print(f"Total time: {total_time:.2f} seconds, FPS: {fps:.2f}")

New https://pypi.org/project/ultralytics/8.2.2 available 😃 Update with 'pip install -U ultralytics'
Ultralytics YOLOv8.1.45 🚀 Python-3.10.14 torch-2.0.1+cu117 CUDA:0 (NVIDIA GeForce RTX 2080, 7979MiB)
engine/trainer: task=detect, mode=train, model=/home/piai/project_yolo/ultralytics/runs/detect/train25/weights/helmet_final.pt, data=coco8.yaml, epochs=100, time=None, patience=100, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=train31, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, bgr=0.0, mosaic=1.0, mixup=0.0, copy_paste=0.0, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=runs/detect/train31

Dataset 'coco8.yaml' images not found ⚠️, missing path '/home/piai/project_yolo/ultralytics/datasets/coco8/images/val'
Downloading https://ultralytics.com/assets/coco8.zip to '/home/piai/project_yolo/ultralytics/datasets/coco8.zip'...

100%|████████████████████████████████████████| 433k/433k [00:00<00:00, 18.2MB/s]
Unzipping /home/piai/project_yolo/ultralytics/datasets/coco8.zip to /home/piai/p

Dataset download success ✅ (2.9s), saved to /home/piai/project_yolo/ultralytics/datasets

Overriding model.yaml nc=1 with nc=80

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    897664  ultralytics.nn.modules.head.Detect           [80, [64, 128, 256]]

Model summary: 225 layers, 3157200 parameters, 3157184 gradients, 8.9 GFLOPs

Transferred 319/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
AMP: checks passed ✅

train: Scanning /home/piai/project_yolo/ultralytics/datasets/coco8/labels/train.

train: New cache created: /home/piai/project_yolo/ultralytics/datasets/coco8/labels/train.cache

val: Scanning /home/piai/project_yolo/ultralytics/datasets/coco8/labels/val... 4

val: New cache created: /home/piai/project_yolo/ultralytics/datasets/coco8/labels/val.cache

Plotting labels to runs/detect/train31/labels.jpg...
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.000119, momentum=0.9) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to runs/detect/train31
Starting training for 100 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      1/100     0.858G      1.931      5.088      2.418         21        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      2/100     0.862G       1.81       4.99      2.303         36        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      3/100     0.862G      2.374      5.443      2.822         20        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      4/100     0.858G      1.651      5.041      2.153         21        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      5/100     0.881G      1.458      4.925      2.023         19        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      6/100     0.883G      1.759      5.138      2.168         22        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      7/100     0.879G      1.703      5.141      2.082         20        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      8/100     0.883G      1.397       4.85      2.016         20        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      9/100     0.881G      1.634      5.078      2.024         20        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     10/100     0.883G      1.511      4.914      2.066         25        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     11/100     0.883G      1.719      4.996      2.204         31        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     12/100     0.883G      1.816      5.107      2.264         31        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     13/100     0.883G      1.724      5.013      2.333         24        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     14/100     0.881G      1.184       4.96      2.025         15        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     15/100     0.883G      1.672      5.003      2.252         38        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     16/100     0.885G      1.923      5.074      2.255         49        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     17/100     0.883G      1.823      5.103      2.257         25        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     18/100     0.879G      1.368      5.022      1.863         16        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     19/100     0.881G      1.954      5.079       2.36         34        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     20/100     0.883G      2.078      5.177      2.228         25        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     21/100     0.885G      1.502      4.915      1.886         26        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     22/100     0.887G      2.147       5.14      2.388         52        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     23/100     0.885G       1.46      4.825      2.077         22        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     24/100     0.883G      1.881       5.05      2.392         34        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     25/100     0.875G      1.888        5.2       2.64         11        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     26/100     0.883G      1.611      4.882      1.886         35        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     27/100     0.883G      1.819      4.976       2.25         24        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     28/100     0.881G       1.92      5.171      2.249         35        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     29/100     0.883G      1.826        5.1      2.117         28        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     30/100     0.883G      1.519      4.957      1.898         29        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     31/100     0.883G      1.845       5.16      2.368         25        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     32/100     0.883G      1.497       4.87      2.172         20        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     33/100     0.883G      1.918       5.13      2.291         31        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     34/100     0.885G      1.434       4.83      2.039         32        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     35/100     0.883G      1.555      4.993      2.089         23        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     36/100     0.883G      1.641      5.068      2.196         34        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     37/100     0.883G      1.628      4.948      2.008         34        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     38/100     0.883G      1.611      4.924      1.743         29        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     39/100     0.885G      1.407      4.879      1.889         25        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     40/100     0.883G      1.867      4.962      2.461         19        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     41/100     0.883G      1.874      5.061      2.235         29        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     42/100     0.883G      1.777       4.94      2.306         34        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     43/100     0.883G      1.409       4.79      2.048         20        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     44/100     0.883G      1.614      4.874      2.068         23        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     45/100     0.885G      1.476      4.753      1.904         40        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     46/100     0.883G      2.096      5.265      2.556         23        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     47/100     0.883G      1.544      5.063      2.066         14        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     48/100     0.883G      1.416      4.937      1.807         31        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     49/100     0.879G      1.587      5.052      2.005         17        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     50/100     0.883G      1.772      4.829      2.247         31        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     51/100     0.883G      1.582      4.833      1.916         35        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     52/100     0.883G      1.524      4.813      1.905         55        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     53/100     0.879G      1.254      4.848       1.62         14        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     54/100     0.885G      1.472      4.796      1.803         46        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     55/100     0.883G      1.473      4.878       1.98         30        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     56/100     0.883G      1.354      4.745      1.973         22        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     57/100     0.883G      1.523      4.713      1.974         28        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     58/100     0.877G       1.34      5.057      2.008         11        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     59/100     0.881G      1.302      4.917      1.977         16        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     60/100     0.885G      1.441      4.753      1.911         30        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     61/100     0.883G      1.401      4.777      1.798         26        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     62/100     0.881G      1.161      4.667      1.581         20        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     63/100     0.877G      1.304      4.789      1.611         16        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     64/100     0.883G      1.697      4.971      1.953         26        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     65/100     0.883G      1.654      4.885      1.974         37        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     66/100     0.885G      1.541      4.791      2.072         51        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     67/100     0.885G      1.643      4.804      2.004         37        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     68/100     0.885G      1.887      4.952      2.116         31        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     69/100     0.885G      1.769      5.151      2.316         12        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     70/100     0.877G      1.979      5.382      2.577          9        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     71/100     0.879G      1.594      4.866      2.118         23        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     72/100     0.881G      1.183       4.72      1.792         21        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     73/100     0.883G      1.371       4.89      2.153         15        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     74/100     0.885G      1.715       4.82      2.301         28        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     75/100     0.881G      1.784      4.822      2.078         60        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     76/100     0.883G       2.07      5.052      2.987         14        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     77/100     0.885G      1.817      4.821      2.155         37        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     78/100     0.885G      1.852      4.815      2.252         45        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     79/100     0.877G       1.88       5.02      2.682         16        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     80/100     0.879G      1.426      4.676      2.215         21        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     81/100     0.889G      1.757      4.779        2.3         42        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     82/100     0.881G      1.614      4.764      2.076         32        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     83/100     0.883G       1.61      4.892      1.876         31        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     84/100     0.885G      1.236      4.723      1.769         30        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     85/100     0.883G      1.361      4.628      1.877         26        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     86/100     0.883G       1.11      4.576      1.722         24        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     87/100     0.883G      1.595      4.625      2.182         31        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     88/100     0.885G      1.546      4.783      1.907         47        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     89/100     0.883G      1.554      4.735       2.04         26        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     90/100     0.883G      1.717      4.917      1.957         31        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

Closing dataloader mosaic

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     91/100     0.883G      1.518      5.024      2.157         13        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     92/100     0.885G      1.414      4.887      2.012         13        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     93/100     0.881G      1.842      5.006      2.552         13        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     94/100     0.883G      1.913      5.115      2.827         13        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     95/100     0.883G      1.632      4.954      2.336         13        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     96/100     0.885G      1.667       5.09      2.357         13        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     97/100     0.881G      1.773       4.96      2.328         13        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     98/100     0.883G      1.796      5.062      2.971         13        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     99/100     0.883G      1.388      4.887      2.143         13        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    100/100     0.883G      1.527      4.863      2.192         13        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

100 epochs completed in 0.014 hours.
Optimizer stripped from runs/detect/train31/weights/last.pt, 6.5MB
Optimizer stripped from runs/detect/train31/weights/best.pt, 6.5MB

Validating runs/detect/train31/weights/best.pt...
Ultralytics YOLOv8.1.45 🚀 Python-3.10.14 torch-2.0.1+cu117 CUDA:0 (NVIDIA GeForce RTX 2080, 7979MiB)
Model summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs

                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

Speed: 0.6ms preprocess, 2.6ms inference, 0.0ms loss, 1.0ms postprocess per image
Results saved to runs/detect/train31

WARNING ⚠️ torch.Tensor inputs should be normalized 0.0-1.0 but max value is 2.640000104904175. Dividing input by 255.
0: 256x256 (no detections), 0.5ms
1: 256x256 (no detections), 0.5ms
2: 256x256 (no detections), 0.5ms
3: 256x256 (no detections), 0.5ms
4: 256x256 (no detections), 0.5ms
5: 256x256 (no detections), 0.5ms
6: 256x256 (no detections), 0.5ms
7: 256x256 (no detections), 0.5ms
8: 256x256 (no detections), 0.5ms
9: 256x256 (no detections), 0.5ms
10: 256x256 (no detections), 0.5ms
11: 256x256 (no detections), 0.5ms
12: 256x256 (no detections), 0.5ms
13: 256x256 (no detections), 0.5ms
14: 256x256 (no detections), 0.5ms
15: 256x256 (no detections), 0.5ms
16: 256x256 (no detections), 0.5ms
17: 256x256 (no detections), 0.5ms
18: 256x256 (no detections), 0.5ms
19: 256x256 (no detections), 0.5ms
20: 256x256 (no detections), 0.5ms
21: 256x256 (no detections), 0.5ms
22: 256x256 (no detections), 0.5ms
23: 256x256 (no detections), 0.5ms
24: 256x256 (no detections), 0.5ms
25: 256x256 (no detections), 0.5ms
26: 256x256 (no detections), 0.5ms
27: 256x256 (no detections), 0.5ms
28: 256x256 (no detections), 0.5ms
29: 256x256 (no detections), 0.5ms
30: 256x256 (no detections), 0.5ms
31: 256x256 (no detections), 0.5ms
Speed: 0.0ms preprocess, 0.5ms inference, 0.3ms postprocess per image at shape (1, 3, 256, 256)
Processed 32 frames in 0.172 seconds.

WARNING ⚠️ torch.Tensor inputs should be normalized 0.0-1.0 but max value is 2.640000104904175. Dividing input by 255.
0: 256x256 (no detections), 0.4ms
1: 256x256 (no detections), 0.4ms
2: 256x256 (no detections), 0.4ms
3: 256x256 (no detections), 0.4ms
4: 256x256 (no detections), 0.4ms
5: 256x256 (no detections), 0.4ms
6: 256x256 (no detections), 0.4ms
7: 256x256 (no detections), 0.4ms
8: 256x256 (no detections), 0.4ms
9: 256x256 (no detections), 0.4ms
10: 256x256 (no detections), 0.4ms
11: 256x256 (no detections), 0.4ms
12: 256x256 (no detections), 0.4ms
13: 256x256 (no detections), 0.4ms
14: 256x256 (no detections), 0.4ms
15: 256x256 (no detections), 0.4ms
16: 256x256 (no detections), 0.4ms
17: 256x256 (no detections), 0.4ms
18: 256x256 (no detections), 0.4ms
19: 256x256 (no detections), 0.4ms
20: 256x256 (no detections), 0.4ms
21: 256x256 (no detections), 0.4ms
22: 256x256 (no detections), 0.4ms
23: 256x256 (no detections), 0.4ms
24: 256x256 (no detections), 0.4ms
25: 256x256 (no detections), 0.4ms
26: 256x256 (no detections), 0.4ms
27: 256x256 (no detections), 0.4ms
28: 256x256 (no detections), 0.4ms
29: 256x256 (no detections), 0.4ms
30: 256x256 (no detections), 0.4ms
31: 256x256 (no detections), 0.4ms
Speed: 0.0ms preprocess, 0.4ms inference, 0.3ms postprocess per image at shape (1, 3, 256, 256)
Processed 32 frames in 0.028 seconds.

WARNING ⚠️ torch.Tensor inputs should be normalized 0.0-1.0 but max value is 2.640000104904175. Dividing input by 255.
0: 256x256 (no detections), 0.4ms
1: 256x256 (no detections), 0.4ms
2: 256x256 (no detections), 0.4ms
3: 256x256 (no detections), 0.4ms
4: 256x256 (no detections), 0.4ms
5: 256x256 (no detections), 0.4ms
6: 256x256 (no detections), 0.4ms
7: 256x256 (no detections), 0.4ms
8: 256x256 (no detections), 0.4ms
9: 256x256 (no detections), 0.4ms
10: 256x256 (no detections), 0.4ms
11: 256x256 (no detections), 0.4ms
12: 256x256 (no detections), 0.4ms
13: 256x256 (no detections), 0.4ms
14: 256x256 (no detections), 0.4ms
15: 256x256 (no detections), 0.4ms
16: 256x256 (no detections), 0.4ms
17: 256x256 (no detections), 0.4ms
18: 256x256 (no detections), 0.4ms
19: 256x256 (no detections), 0.4ms
20: 256x256 (no detections), 0.4ms
21: 256x256 (no detections), 0.4ms
22: 256x256 (no detections), 0.4ms
23: 256x256 (no detections), 0.4ms
24: 256x256 (no detections), 0.4ms
25: 256x256 (no detections), 0.4ms
26: 256x256 (no detections), 0.4ms
27: 256x256 (no detections), 0.4ms
28: 256x256 (no detections), 0.4ms
29: 256x256 (no detections), 0.4ms
30: 256x256 (no detections), 0.4ms
31: 256x256 (no detections), 0.4ms
Speed: 0.0ms preprocess, 0.4ms inference, 0.2ms postprocess per image at shape (1, 3, 256, 256)
Processed 32 frames in 0.027 seconds.

WARNING ⚠️ torch.Tensor inputs should be normalized 0.0-1.0 but max value is 2.640000104904175. Dividing input by 255.
0: 256x256 (no detections), 0.4ms
1: 256x256 (no detections), 0.4ms
2: 256x256 (no detections), 0.4ms
3: 256x256 (no detections), 0.4ms
4: 256x256 (no detections), 0.4ms
5: 256x256 (no detections), 0.4ms
6: 256x256 (no detections), 0.4ms
7: 256x256 (no detections), 0.4ms
8: 256x256 (no detections), 0.4ms
9: 256x256 (no detections), 0.4ms
10: 256x256 (no detections), 0.4ms
11: 256x256 (no detections), 0.4ms
12: 256x256 (no detections), 0.4ms
13: 256x256 (no detections), 0.4ms
14: 256x256 (no detections), 0.4ms
15: 256x256 (no detections), 0.4ms
16: 256x256 (no detections), 0.4ms
17: 256x256 (no detections), 0.4ms
18: 256x256 (no detections), 0.4ms
19: 256x256 (no detections), 0.4ms
20: 256x256 (no detections), 0.4ms
21: 256x256 (no detections), 0.4ms
22: 256x256 (no detections), 0.4ms
23: 256x256 (no detections), 0.4ms
24: 256x256 (no detections), 0.4ms
25: 256x256 (no detections), 0.4ms
26: 256x256 (no detections), 0.4ms
27: 256x256 (no detections), 0.4ms
28: 256x256 (no detections), 0.4ms
29: 256x256 (no detections), 0.4ms
30: 256x256 (no detections), 0.4ms
31: 256x256 (no detections), 0.4ms
Speed: 0.0ms preprocess, 0.4ms inference, 0.2ms postprocess per image at shape (1, 3, 256, 256)
Processed 32 frames in 0.025 seconds.

WARNING ⚠️ torch.Tensor inputs should be normalized 0.0-1.0 but max value is 2.640000104904175. Dividing input by 255.
0: 256x256 (no detections), 0.4ms
1: 256x256 (no detections), 0.4ms
2: 256x256 (no detections), 0.4ms
3: 256x256 (no detections), 0.4ms
4: 256x256 (no detections), 0.4ms
5: 256x256 (no detections), 0.4ms
6: 256x256 (no detections), 0.4ms
7: 256x256 (no detections), 0.4ms
8: 256x256 (no detections), 0.4ms
9: 256x256 (no detections), 0.4ms
10: 256x256 (no detections), 0.4ms
11: 256x256 (no detections), 0.4ms
12: 256x256 (no detections), 0.4ms
13: 256x256 (no detections), 0.4ms
14: 256x256 (no detections), 0.4ms
15: 256x256 (no detections), 0.4ms
16: 256x256 (no detections), 0.4ms
17: 256x256 (no detections), 0.4ms
18: 256x256 (no detections), 0.4ms
19: 256x256 (no detections), 0.4ms
20: 256x256 (no detections), 0.4ms
21: 256x256 (no detections), 0.4ms
22: 256x256 (no detections), 0.4ms
23: 256x256 (no detections), 0.4ms
24: 256x256 (no detections), 0.4ms
25: 256x256 (no detections), 0.4ms
26: 256x256 (no detections), 0.4ms
27: 256x256 (no detections), 0.4ms
28: 256x256 (no detections), 0.4ms
29: 256x256 (no detections), 0.4ms
30: 256x256 (no detections), 0.4ms
31: 256x256 (no detections), 0.4ms
Speed: 0.0ms preprocess, 0.4ms inference, 0.2ms postprocess per image at shape (1, 3, 256, 256)
Processed 32 frames in 0.025 seconds.

WARNING ⚠️ torch.Tensor inputs should be normalized 0.0-1.0 but max value is 2.640000104904175. Dividing input by 255.
0: 256x256 (no detections), 0.4ms
1: 256x256 (no detections), 0.4ms
2: 256x256 (no detections), 0.4ms
3: 256x256 (no detections), 0.4ms
4: 256x256 (no detections), 0.4ms
5: 256x256 (no detections), 0.4ms
6: 256x256 (no detections), 0.4ms
7: 256x256 (no detections), 0.4ms
8: 256x256 (no detections), 0.4ms
9: 256x256 (no detections), 0.4ms
10: 256x256 (no detections), 0.4ms
11: 256x256 (no detections), 0.4ms
12: 256x256 (no detections), 0.4ms
13: 256x256 (no detections), 0.4ms
14: 256x256 (no detections), 0.4ms
15: 256x256 (no detections), 0.4ms
16: 256x256 (no detections), 0.4ms
17: 256x256 (no detections), 0.4ms
18: 256x256 (no detections), 0.4ms
19: 256x256 (no detections), 0.4ms
20: 256x256 (no detections), 0.4ms
21: 256x256 (no detections), 0.4ms
22: 256x256 (no detections), 0.4ms
23: 256x256 (no detections), 0.4ms
24: 256x256 (no detections), 0.4ms
25: 256x256 (no detections), 0.4ms
26: 256x256 (no detections), 0.4ms
27: 256x256 (no detections), 0.4ms
28: 256x256 (no detections), 0.4ms
29: 256x256 (no detections), 0.4ms
30: 256x256 (no detections), 0.4ms
Speed: 0.0ms preprocess, 0.4ms inference, 0.3ms postprocess per image at shape (1, 3, 256, 256)
Processed 31 frames in 0.028 seconds.
Total time: 65.60 seconds, FPS: 2.91

## 경량화

In [ ]:
import torch, torch.nn as nn
from torch.nn.utils import prune
from ultralytics import YOLO

model = YOLO("/home/piai/project_yolo/ultralytics/runs/detect/train25/weights/helmet_final.pt")

def sparsity(model):
    # 모델의 전체 sparsity 계산
    total_elements, zero_elements = 0, 0
    for p in model.parameters():
        total_elements += p.numel()
        zero_elements += (p == 0).sum().item()
    return zero_elements / total_elements

pruning_param = 0.1  # 점진적인 pruning을 위해 비율 감소

# 프루닝된 가중치를 영구적으로 제거
for name, module in model.model.named_modules():
    if isinstance(module, nn.Conv2d) or isinstance(module, nn.Linear):
        if hasattr(module, 'weight_mask'):
            prune.remove(module, 'weight')

In [ ]:
# Sparsity 확인
print(f'Model pruned to {sparsity(model.model):.3g} global sparsity')

Model pruned to 6.64e-07 global sparsity

In [ ]:
ckpt = {
    'model': model.model,
    'train_args': {},  # 훈련 인자 저장
}

In [ ]:
torch.save(ckpt, '/home/piai/project_yolo/ultralytics/runs/detect/train25/weights/helmet_pruned.pt')

In [ ]:
!pwd

/home/piai/project_yolo/ultralytics

In [ ]:
model = YOLO("/home/piai/project_yolo/ultralytics/runs/detect/train25/weights/helmet_pruned.pt")

In [ ]:
# 모델의 총 파라미터 수 계산
total_params = sum(p.numel() for p in model.parameters())

# 모델의 학습 가능한 총 파라미터 수 계산
trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)

print(f"Total Parameters: {total_params}")
print(f"Trainable Parameters: {trainable_params}")

Total Parameters: 3011043
Trainable Parameters: 0

In [ ]:

class HelmetDataset(Dataset):
    def __init__(self, img_list, txt_list, transform=None):
        self.img_list = img_list
        self.txt_list = txt_list
        self.transform = transform

    def __len__(self):
        return len(self.img_list)

    def __getitem__(self, idx):
        img_path = self.img_list[idx]
        img = cv2.imread(img_path)
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

        if self.transform:
            img = self.transform(img)

        return img

# Transforms
transform = transforms.Compose([
    transforms.ToPILImage(),  # OpenCV로 로드된 이미지를 PIL 이미지로 변환
    transforms.Resize((256, 256)),  # 이미지 크기 조정
    transforms.ToTensor(),  # 텐서로 변환
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])  # 정규화
])

# 데이터셋 및 데이터 로더 설정
test_img_list = glob('/home/piai/project_yolo/ultralytics/poskick_helmet_7/test/images/*.jpg')
test_dataset = HelmetDataset(test_img_list, [], transform=transform)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

# # 모델 정의 (여기서는 가상의 모델로 예시)
model = YOLO("/home/piai/project_yolo/ultralytics/runs/detect/train25/weights/helmet_pruned.pt")
# model = model.to('cuda' if torch.cuda.is_available() else 'cpu')

# FPS 측정
start_time = time.time()
num_frames = 0

model.eval()
with torch.no_grad():
    for images in test_loader:
        images = images.to('cuda' if torch.cuda.is_available() else 'cpu')
        start = time.time()
        _ = model(images)  # 모델 예측 (실제 모델 사용시 변경)
        end = time.time()
        num_frames += images.size(0)
        print(f"Processed {images.size(0)} frames in {end - start:.3f} seconds.")

total_time = time.time() - start_time
fps = num_frames / total_time
print(f"Total time: {total_time:.2f} seconds, FPS: {fps:.2f}")

New https://pypi.org/project/ultralytics/8.2.2 available 😃 Update with 'pip install -U ultralytics'
Ultralytics YOLOv8.1.45 🚀 Python-3.10.14 torch-2.0.1+cu117 CUDA:0 (NVIDIA GeForce RTX 2080, 7979MiB)
engine/trainer: task=detect, mode=train, model=/home/piai/project_yolo/ultralytics/runs/detect/train25/weights/helmet_pruned.pt, data=coco8.yaml, epochs=100, time=None, patience=100, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=train29, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, bgr=0.0, mosaic=1.0, mixup=0.0, copy_paste=0.0, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=runs/detect/train29
Overriding model.yaml nc=1 with nc=80

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    897664  ultralytics.nn.modules.head.Detect           [80, [64, 128, 256]]
Model summary: 225 layers, 3157200 parameters, 3157184 gradients, 8.9 GFLOPs

Transferred 319/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
AMP: checks passed ✅

train: Scanning /home/piai/project_yolo/ultralytics/datasets/coco8/labels/train.
val: Scanning /home/piai/project_yolo/ultralytics/datasets/coco8/labels/val.cach

Plotting labels to runs/detect/train29/labels.jpg...

Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7feaea7d27a0>
Traceback (most recent call last):
  File "/home/piai/anaconda3/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/piai/anaconda3/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1442, in _shutdown_workers
    w.join(timeout=_utils.MP_STATUS_CHECK_INTERVAL)
  File "/home/piai/anaconda3/lib/python3.10/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/home/piai/anaconda3/lib/python3.10/multiprocessing/popen_fork.py", line 40, in wait
    if not wait([self.sentinel], timeout):
  File "/home/piai/anaconda3/lib/python3.10/multiprocessing/connection.py", line 931, in wait
    ready = selector.select(timeout)
  File "/home/piai/anaconda3/lib/python3.10/selectors.py", line 416, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt:

optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.000119, momentum=0.9) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to runs/detect/train29
Starting training for 100 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      1/100     0.669G      1.931      5.088      2.418         21        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      2/100     0.705G       1.81       4.99      2.303         36        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      3/100     0.696G      2.374      5.443      2.822         20        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      4/100     0.698G      1.651      5.041      2.153         21        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      5/100     0.717G      1.458      4.925      2.023         19        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      6/100     0.717G      1.759      5.138      2.168         22        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      7/100     0.724G      1.703      5.141      2.082         20        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      8/100     0.719G      1.397       4.85      2.016         20        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      9/100     0.717G      1.634      5.078      2.024         20        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     10/100     0.717G      1.511      4.914      2.066         25        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     11/100     0.717G      1.719      4.996      2.204         31        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     12/100     0.717G      1.816      5.107      2.264         31        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     13/100     0.719G      1.724      5.013      2.333         24        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     14/100     0.717G      1.184       4.96      2.025         15        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     15/100     0.728G      1.672      5.003      2.252         38        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     16/100     0.726G      1.923      5.074      2.255         49        640: 1
                 Class     Images  Instances      Box(P          R      mAP50  m

                   all          4         17          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

  0%|          | 0/1 [00:05<?, ?it/s]

RuntimeError: DataLoader worker (pid(s) 29554, 29555, 29556, 29557, 29558, 29559, 29560, 29561) exited unexpectedly

In [ ]:
# Benchmark on GPU
benchmark(model='/home/piai/project_yolo/ultralytics/runs/detect/train25/weights/helmet_pruned.pt', data='/home/piai/project_yolo/ultralytics/poskick_helmet_7/data.yaml', imgsz=640, half=False, device=0)

Setup complete ✅ (8 CPUs, 62.5 GB RAM, 133.9/233.2 GB disk)

Benchmarks complete for helmet_pruned.pt on /home/piai/project_yolo/ultralytics/poskick_helmet_7/data.yaml at imgsz=640 (347.07s)
                   Format Status❔  Size (MB)  metrics/mAP50-95(B)  Inference time (ms/im)
0                 PyTorch       ✅       11.8               0.8769                   10.12
1             TorchScript       ✅       11.9               0.8746                    4.93
2                    ONNX       ✅       11.7               0.8746                    6.45
3                OpenVINO       ❌        0.0                  NaN                     NaN
4                TensorRT       ❎       14.6                  NaN                     NaN
5                  CoreML       ❌        0.0                  NaN                     NaN
6   TensorFlow SavedModel       ❌        0.0                  NaN                     NaN
7     TensorFlow GraphDef       ❌        0.0                  NaN                     NaN
8         TensorFlow Lite       ❌        0.0                  NaN                     NaN
9     TensorFlow Edge TPU       ❌        0.0                  NaN                     NaN
10          TensorFlow.js       ❌        0.0                  NaN                     NaN
11           PaddlePaddle       ✅       23.3               0.8746                  293.07
12                   NCNN       ✅       11.6               0.8746                   86.93

                   Format Status❔  Size (MB)  metrics/mAP50-95(B)  Inference time (ms/im)
0                 PyTorch       ✅       11.8               0.8769                   10.12
1             TorchScript       ✅       11.9               0.8746                    4.93
2                    ONNX       ✅       11.7               0.8746                    6.45
3                OpenVINO       ❌        0.0                  NaN                     NaN
4                TensorRT       ❎       14.6                  NaN                     NaN
5                  CoreML       ❌        0.0                  NaN                     NaN
6   TensorFlow SavedModel       ❌        0.0                  NaN                     NaN
7     TensorFlow GraphDef       ❌        0.0                  NaN                     NaN
8         TensorFlow Lite       ❌        0.0                  NaN                     NaN
9     TensorFlow Edge TPU       ❌        0.0                  NaN                     NaN
10          TensorFlow.js       ❌        0.0                  NaN                     NaN
11           PaddlePaddle       ✅       23.3               0.8746                  293.07
12                   NCNN       ✅       11.6               0.8746                   86.93

## 끝

In [ ]:
!yolo predict source=/home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images save_txt model=/home/piai/project_yolo/ultralytics/runs/detect/train23/weights/helmet_pruned.pt

Ultralytics YOLOv8.0.196 🚀 Python-3.10.14 torch-2.0.1+cu117 CUDA:0 (NVIDIA GeForce RTX 2080, 7979MiB)
Model summary (fused): 168 layers, 3005843 parameters, 0 gradients, 8.1 GFLOPs

image 1/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/005323_jpg.rf.f6c74b5ecde80b32199721e6c0c1fb1c.jpg: 640x640 6 helmets, 5.9ms
image 2/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/005336_jpg.rf.4f58d3457ae49cdef9ebf2e96a9f51fd.jpg: 640x640 9 helmets, 5.4ms
image 3/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/005344_jpg.rf.9f56d5a636f9569816dfba64c1169043.jpg: 640x640 6 helmets, 5.2ms
image 4/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/005418_jpg.rf.833c02245835bb811f2fba2b7ba2bcf1.jpg: 640x640 6 helmets, 5.5ms
image 5/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/006067_jpg.rf.2bc692265d4ab2203a53271168bc2429.jpg: 640x640 9 helmets, 5.5ms
image 6/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/006232_jpg.rf.8d883cea41d022d5692ed76aeb35fa0a.jpg: 640x640 2 helmets, 6.1ms
image 7/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/0_10645338_jpg.rf.0df6224f5d7448bd0da553711c2b522b.jpg: 640x640 1 helmet, 4.9ms
image 8/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/0_15574275_jpg.rf.23f2db624ab9e5d74a7a823d9922322a.jpg: 640x640 1 helmet, 5.4ms
image 9/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/0_17570790_jpg.rf.9ce7c13ee09210ff89ee86133b3aa76f.jpg: 640x640 1 helmet, 5.4ms
image 10/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/0_19421787_jpg.rf.e912db4756c8890744561586e5f80648.jpg: 640x640 1 helmet, 5.0ms
image 11/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/0_20591666_jpg.rf.80e6d3202a35b675f338885749e24684.jpg: 640x640 1 helmet, 6.1ms
image 12/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/0_24207349_jpg.rf.651a5132d79e01ff39805e2fd91c7ddc.jpg: 640x640 1 helmet, 5.3ms
image 13/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/0_29516002_jpg.rf.8b055b0f981b7036bec039232e49fe64.jpg: 640x640 1 helmet, 5.1ms
image 14/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/0_35427851_jpg.rf.1fb8761a67ada4486f4b318fbdb427a2.jpg: 640x640 1 helmet, 6.4ms
image 15/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/0_39693815_jpg.rf.2a246272ce3088fc579138466914a120.jpg: 640x640 2 helmets, 5.2ms
image 16/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/0_41096924_jpg.rf.7cbdb283358d715d92856671eab915a1.jpg: 640x640 1 helmet, 5.5ms
image 17/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/0_41108877_jpg.rf.6afc966cb9b30859b1fcbc152543aef6.jpg: 640x640 1 helmet, 5.4ms
image 18/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/0_41770728_jpg.rf.84d8baf1b90478275ecde853a89dfdbe.jpg: 640x640 1 helmet, 5.3ms
image 19/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/0_54378637_jpg.rf.887845a10f7d8d3875554b73c0a1ffec.jpg: 640x640 1 helmet, 6.0ms
image 20/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/0_57219730_jpg.rf.7b2a59767359fc34d229753492afcd6e.jpg: 640x640 1 helmet, 5.8ms
image 21/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/0_61556113_jpg.rf.701030c05e8cf59705d48a3d1bed53ca.jpg: 640x640 1 helmet, 5.2ms
image 22/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/0_65680209_jpg.rf.096cfeacb93fdab37c7931a554832e81.jpg: 640x640 1 helmet, 5.1ms
image 23/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/0_68428129_jpg.rf.92a8868da2ed8a1d7f6392ddbe53a1a1.jpg: 640x640 1 helmet, 5.2ms
image 24/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/0_68529308_jpg.rf.a4ea92894c30329fd727abb0c6d62dd5.jpg: 640x640 1 helmet, 7.1ms
image 25/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/0_78284334_jpg.rf.61ed47ec43ae454c6284a88cfcdc8588.jpg: 640x640 1 helmet, 7.6ms
image 26/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/0_79073078_jpg.rf.4dc2c8457386b9d12ead421bba10dec6.jpg: 640x640 1 helmet, 5.3ms
image 27/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/0_90525429_jpg.rf.7921de3f349a481bc044b6b57e20a694.jpg: 640x640 1 helmet, 7.6ms
image 28/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/0_91623361_jpg.rf.f23ee6f9fe5e1b40b7dc27b84753deb5.jpg: 640x640 1 helmet, 5.8ms
image 29/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/0_97581590_jpg.rf.8860d3bbd3aa604cb4ba9e2a4b20d503.jpg: 640x640 1 helmet, 6.6ms
image 30/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/1_14461871_jpg.rf.a46dc2c087f322fe5cf169abe77425c2.jpg: 640x640 1 helmet, 5.2ms
image 31/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/1_39756346_jpg.rf.c29339cabeb9135bd8b3318c086324b9.jpg: 640x640 1 helmet, 5.5ms
image 32/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/1_53644045_jpg.rf.6a24fb628eb346b36c39f9c2ed50b0c0.jpg: 640x640 1 helmet, 6.0ms
image 33/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/1_53671292_jpg.rf.fc62d02bd5e8ab47ad819ccd7fbb57cf.jpg: 640x640 1 helmet, 6.5ms
image 34/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/1_76090231_jpg.rf.00c8f48c9147e66971d80251665f74b7.jpg: 640x640 1 helmet, 6.5ms
image 35/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/1_81039173_jpg.rf.f5c3c49ba09ab014c034408a94efc1d4.jpg: 640x640 1 helmet, 7.1ms
image 36/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/1_85709072_jpg.rf.aafebf84f8bbef8ce0f21763f1a435a7.jpg: 640x640 1 helmet, 6.2ms
image 37/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/1_88044476_jpg.rf.9c80f370a960d58d171e1b11424562a3.jpg: 640x640 1 helmet, 6.4ms
image 38/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/1_92501512_jpg.rf.94c25b21875c9cb090b10539335bd96a.jpg: 640x640 1 helmet, 6.6ms
image 39/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/1_96283997_jpg.rf.ba8c8093327b6317dda4c08398095c8b.jpg: 640x640 1 helmet, 8.0ms
image 40/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/20221206_094829_jpg.rf.35fa9c9677425cc520aea47222284d5b.jpg: 640x640 2 helmets, 6.6ms
image 41/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/20221206_094844_jpg.rf.ff0265d79579ac991ec3a3b7e62b51c2.jpg: 640x640 1 helmet, 6.3ms
image 42/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/20221206_094924_jpg.rf.bf6845d67480525e4145e04a4c95becb.jpg: 640x640 2 helmets, 8.1ms
image 43/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/20221206_094930_jpg.rf.e2c0dba4f7ce4e5b685546f771564c57.jpg: 640x640 2 helmets, 7.2ms
image 44/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/20221206_095153_jpg.rf.9d5b830ba3c05df4195959f5b10cdc3d.jpg: 640x640 2 helmets, 6.7ms
image 45/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/20221206_095429_jpg.rf.9906972886a0439b93842c6dd76f10bb.jpg: 640x640 1 helmet, 5.3ms
image 46/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/20221206_095432_jpg.rf.b31c4fc078a3f406a9e0ec581273df4e.jpg: 640x640 1 helmet, 5.1ms
image 47/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/20221206_095437_jpg.rf.f5f3e45c93b569f293e1e2739a506c76.jpg: 640x640 1 helmet, 5.6ms
image 48/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/20221206_095543_jpg.rf.2c468e791c7309f4e4658055d9f30aec.jpg: 640x640 2 helmets, 5.1ms
image 49/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/20221206_095630_jpg.rf.d7db57f16b08107dc547cf535c3978ed.jpg: 640x640 2 helmets, 5.6ms
image 50/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/20221206_095934_jpg.rf.4ab8262b99c7f2d6b561c29e4a16b58b.jpg: 640x640 3 helmets, 6.1ms
image 51/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/20221206_095944_jpg.rf.6fd17256c5c925af946793aa69795227.jpg: 640x640 1 helmet, 7.2ms
image 52/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/20221206_100044_jpg.rf.9c3b403f2c638b08a3b4e876f2be89c1.jpg: 640x640 2 helmets, 6.7ms
image 53/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/20221206_100057_jpg.rf.cce139166ce644447a34188853a83ccd.jpg: 640x640 1 helmet, 8.4ms
image 54/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/20221206_100153_jpg.rf.d027b24d8eecc5ae0e92b737fb1012ff.jpg: 640x640 2 helmets, 5.9ms
image 55/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/20221206_100156_jpg.rf.7192112542c1c3970b3f1eeeda1d9107.jpg: 640x640 2 helmets, 6.4ms
image 56/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/20221206_100251_jpg.rf.c881e15f7fa608f4dd5021c1700ed75d.jpg: 640x640 1 helmet, 5.8ms
image 57/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/20221206_100420_jpg.rf.a9dac90574f59d6b4d0625aaa4b0a88e.jpg: 640x640 2 helmets, 6.2ms
image 58/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/20221206_100559_jpg.rf.8826cb1c90c7d9e6cd0259cbe4cd0174.jpg: 640x640 1 helmet, 5.3ms
image 59/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/20221206_100834_jpg.rf.01e3fe08331df1dce3462b62e98fb8ed.jpg: 640x640 2 helmets, 6.5ms
image 60/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/20221206_100917_jpg.rf.591df8471486a69ecd1f13875602b3e5.jpg: 640x640 2 helmets, 5.6ms
image 61/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/20221206_100933_jpg.rf.1f7cf076d9038d1e248462426d9203bd.jpg: 640x640 1 helmet, 6.2ms
image 62/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/20221206_100949_jpg.rf.85775f65588cf6a9f81dd55e6d28cb13.jpg: 640x640 2 helmets, 5.4ms
image 63/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/2_0_10589351_jpg.rf.54050da8fde4f0c87f0a505ff737e41b.jpg: 640x640 1 helmet, 6.7ms
image 64/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/2_0_27903295_jpg.rf.a6a6d8604f907719e89bf0a3feaad1c3.jpg: 640x640 1 helmet, 5.8ms
image 65/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/2_0_42712982_jpg.rf.3642808140e719e748f4bf3b6c7d235e.jpg: 640x640 1 helmet, 5.6ms
image 66/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/2_0_45261771_jpg.rf.fb2d761afd0ad8aa9ec9e97d67055eda.jpg: 640x640 1 helmet, 5.7ms
image 67/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/2_0_54633021_jpg.rf.9ac9b4e048d92850cd950a3d708c99fe.jpg: 640x640 1 helmet, 5.5ms
image 68/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/2_0_54839771_jpg.rf.626c2eb2d9f848c30c4db4e630a04f4e.jpg: 640x640 1 helmet, 5.2ms
image 69/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/2_0_54894178_jpg.rf.2683180cc57713f0a39b6992dadce365.jpg: 640x640 1 helmet, 6.3ms
image 70/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/2_0_56894587_jpg.rf.630a72a92be19fe31d953c99d9dc0a8f.jpg: 640x640 1 helmet, 5.3ms
image 71/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/2_0_58730809_jpg.rf.6b8d2f924f5cb1d8f9dbf9564f02af4b.jpg: 640x640 1 helmet, 8.5ms
image 72/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/2_0_59139622_jpg.rf.ef2c341bc9a5a235b43675b3c03d6464.jpg: 640x640 1 helmet, 5.0ms
image 73/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/2_0_63253615_jpg.rf.d8e5431b55ee1c0a9a580e5009215ab1.jpg: 640x640 1 helmet, 7.7ms
image 74/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/2_0_67064674_jpg.rf.1b61daf1a7860ea75abd943b7f23d33e.jpg: 640x640 1 helmet, 5.7ms
image 75/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/2_0_67517076_jpg.rf.85bcd0b1ecd9d0f88e6780518ee4e811.jpg: 640x640 1 helmet, 5.5ms
image 76/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/2_0_68894362_jpg.rf.48ca1cf1138c44905849e753f6839aee.jpg: 640x640 1 helmet, 6.0ms
image 77/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/2_0_83005211_jpg.rf.10909d5b9ceb123345893beacd906e3f.jpg: 640x640 1 helmet, 5.9ms
image 78/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/2_0_83056912_jpg.rf.b001d80a49cc5a85d26275c4d198578b.jpg: 640x640 1 helmet, 5.4ms
image 79/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/2_0_83903659_jpg.rf.d6dea9822fdfdef4bb213fecba82a023.jpg: 640x640 1 helmet, 5.2ms
image 80/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/2_43926070_jpg.rf.cf6f61b4564e825c251c3cf994c08388.jpg: 640x640 1 helmet, 5.2ms
image 81/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/2_60349824_jpg.rf.06d11970e9c084f15f9e4c158ad5e30f.jpg: 640x640 1 helmet, 6.5ms
image 82/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/2_66094202_jpg.rf.300777e84aff0309c0533325aa12cd41.jpg: 640x640 1 helmet, 6.5ms
image 83/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/2_89400142_jpg.rf.61f11f21ecdfa6a63d6f0c1c4ab35c50.jpg: 640x640 1 helmet, 6.6ms
image 84/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/3_12405489_jpg.rf.5777b082f7f0a29940dd6e3a42f31bfa.jpg: 640x640 1 helmet, 7.8ms
image 85/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/3_75033694_jpg.rf.e858ecc03651e17bcb82b55a114ec14f.jpg: 640x640 1 helmet, 5.2ms
image 86/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/4857-Sayili-Is-Kanunu-Doneminde-Isveren-ve-Iscileri_jpg.rf.b91e2162ffaad53f8fcb2d4eff1e47cd.jpg: 640x640 1 helmet, 6.1ms
image 87/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/4_15270294_jpg.rf.048f5bc3bf7cfc4666fb8605ce1870a8.jpg: 640x640 1 helmet, 6.1ms
image 88/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/5_14849078_jpg.rf.d2cf1be408632c00c3fa47b4287381b9.jpg: 640x640 1 helmet, 6.3ms
image 89/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/5_56704289_jpg.rf.39a6bf6428290b9022a4333acc12ed62.jpg: 640x640 1 helmet, 5.7ms
image 90/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/6331-Sayili-Is-Sagligi-ve-Is-Guvenligi-Kanunu_yythk_jpg.rf.32e8f9cf0367c53bf645a72273014e25.jpg: 640x640 1 helmet, 6.2ms
image 91/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/6_40880203_jpg.rf.636c95c1c19e146a7e3d77c8a15fe8f1.jpg: 640x640 1 helmet, 5.6ms
image 92/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/7_24207349_jpg.rf.6db91a9ea2c0eaf1bf9c50188ef60668.jpg: 640x640 1 helmet, 5.5ms
image 93/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/7_56698076_jpg.rf.6ae800382953796b413655655149bf26.jpg: 640x640 1 helmet, 5.9ms
image 94/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/Anilar-Duayen-Bir-Duayenin-Safety-First-Once_yyth_jpg.rf.7958bd6f137bbbccc21b5669d4b6da64.jpg: 640x640 1 helmet, 5.1ms
image 95/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/BARET-MUHENDIS-IS-KASKI-BAKIR-RENK-METAL-3-1-_jpg.rf.034c9ced275b7a6ad239ac069c9afd18.jpg: 640x640 1 helmet, 5.8ms
image 96/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/Baret-Is-Ayakkabisi_jpg.rf.a0ecde44238ae9524f4b0c527c6201f5.jpg: 640x640 4 helmets, 5.3ms
image 97/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/Baret-Modelleri-ve-Fiyatlari-_-Is-Guvenligi-Malzeme-10-_jpg.rf.635e17a87d023c1172aacb3d70cedc16.jpg: 640x640 1 helmet, 6.4ms
image 98/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/Baret-Modelleri-ve-Fiyatlari-_-Is-Guvenligi-Malzeme-4-_jpg.rf.ae2316871ee89251ab378e69b9897cc3.jpg: 640x640 1 helmet, 5.0ms
image 99/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/Baret-Modelleri-ve-Fiyatlari-_-Is-Guvenligi-Malzeme-5-_jpg.rf.79bdc054db200fe3d9fc569d9ecad5cf.jpg: 640x640 1 helmet, 5.0ms
image 100/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/Baret-Nedir_-Teknik-ve-Tasarim-Ozellikleri-1-_png_jpg.rf.89de29e687d9d3d987c12144a32a5777.jpg: 640x640 1 helmet, 6.4ms
image 101/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/Baret-ve-Kasklar-_-Is-Guvenligi-Ekipmanlari-__yythk-4-_jpg.rf.2c757fe8c50f0f823bd170b2ad6095f1.jpg: 640x640 1 helmet, 5.2ms
image 102/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/Baretler_-Oyunun-Kurallari-Degisiyor_jpg.rf.6afae8bd14edfefdcd1261d81bfa9c5a.jpg: 640x640 1 helmet, 5.3ms
image 103/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/CAMP-0202-ROCKSTAR-Dagcilik-Kaski-Sonak-Is_yythkg_jpg.rf.a1cc0c5e90f830a2514150710aed58bc.jpg: 640x640 1 helmet, 5.2ms
image 104/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/Drager-HPS-7000-Itfaiyeci-Kaski-_-Eksen-is-1-_png_jpg.rf.a5ab695aa3c2394a04a2a3010e2342d4.jpg: 640x640 1 helmet, 5.4ms
image 105/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/Dusuk-Fiyat-Garantili-Kaliteli-Is-Sanayi-Emniyet-Ka_jpg.rf.063519f628b608a885c62fe6d581c29c.jpg: 640x640 2 helmets, 6.5ms
image 106/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/FRP-emniyet-kaski-insaat-koruyucu-kask-Anti-smashin-1-_jpg.rf.0882153f7c22fb63d462a2ab0d3fcaf5.jpg: 640x640 1 helmet, 6.2ms
image 107/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/Guvenlik-Koruyucu-Kask-Insaat-Guvenligi-Is-Kaski-Ay-2-_jpeg_jpg.rf.136a9daeb7c17d429ffa705748a7316d.jpg: 640x640 1 helmet, 5.1ms
image 108/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/Guvenlik-koruyucu-baret-insaat-guvenlik-is-ekipmanlari_yyt-1-_jpg.rf.76f98474cb407c5b41058e4810cc3f0e.jpg: 640x640 7 helmets, 5.9ms
image 109/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/Guvenlik-koruyucu-baret-insaat-guvenlik-is-ekipmanlari_yyt-3-_jpg.rf.c65b7d0f562609460951cdef6cd67d72.jpg: 640x640 2 helmets, 5.4ms
image 110/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/Guvenlik-koruyucu-baret-insaat-guvenlik-is-ekipmanlari_yyt_jpg.rf.d6d1c98befa3abd9496bada6c4abeea7.jpg: 640x640 4 helmets, 7.5ms
image 111/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/IMG_7488_jpeg.rf.21cc03ba0d76271d6912c2a53a622ad0.jpg: 640x640 2 helmets, 6.7ms
image 112/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/IMG_7502_jpeg.rf.3a48ab6cf2c603cc0f6cb4d2a7805348.jpg: 640x640 1 helmet, 7.6ms
image 113/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/IMG_7506_jpeg.rf.a80a72539b8bb58bd10bd036328e0571.jpg: 640x640 1 helmet, 6.1ms
image 114/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/IMG_7511_jpeg.rf.7a97c0f30525ca033f0e9e851b132ffc.jpg: 640x640 1 helmet, 7.0ms
image 115/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/IMG_7512_jpeg.rf.a5d4c3e147ab14e25cefab6af5bac446.jpg: 640x640 1 helmet, 5.6ms
image 116/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/IMG_7517_jpeg.rf.5fc3ec51bfa4cc0bdc4577baceda3b90.jpg: 640x640 1 helmet, 5.8ms
image 117/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/IMG_7538_jpeg.rf.9fd501868e916de2a08ba84ac07808b1.jpg: 640x640 1 helmet, 6.1ms
image 118/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/IMG_7544_jpeg.rf.a2d429fc754eaae13d7923184ced590b.jpg: 640x640 1 helmet, 6.2ms
image 119/180 /home/piai/project_yolo/ultralytics/poskick_helmet_5/test/images/IMG_7545_jpeg.rf.24d418b93774f98e66758e6d03a7f0be.jpg: 640x640 1 helmet, 5.2ms

In [ ]:
def measure_fps(model, val_loader, device):
    start_time = time.time()
    num_frames = 0
    model.eval()
    with torch.no_grad():
        for images in val_loader:
            images = images.to(device)
            start = time.time()
            predictions = model(images)
            end = time.time()
            num_frames += 1
            print(f"Frame {num_frames}: {end - start:.3f} seconds")

    total_time = time.time() - start_time
    print(f"Average inference time: {total_time / num_frames:.3f} seconds")
    print(f"FPS: {num_frames / total_time:.2f}")

# 예를 들어 모델 평가 후 FPS 측정
measure_fps(model, test_loader, device)

## test

In [ ]:
!python detect.py --weights helmet_final.pt --img 640 --conf 0.25 --source /home/piai/project_yolo/ultralytics/poskick_helmet_7/test

python: can't open file '/home/piai/project_yolo/ultralytics/detect.py': [Errno 2] No such file or directory

In [ ]:
!yolo detect test source=/home/piai/project_yolo/ultralytics/poskick_helmet_5/test model=helmet_plus200.pt epochs=100 imgsz=640 lr0=0.01 device=0

Traceback (most recent call last):
  File "/home/piai/anaconda3/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/piai/anaconda3/lib/python3.10/site-packages/ultralytics/cfg/__init__.py", line 382, in entrypoint
    check_dict_alignment(full_args_dict, {a: ''})
  File "/home/piai/anaconda3/lib/python3.10/site-packages/ultralytics/cfg/__init__.py", line 203, in check_dict_alignment
    raise SyntaxError(string + CLI_HELP_MSG) from e
SyntaxError: 'test' is not a valid YOLO argument. Similar arguments are i.e. ['detect'].

    Arguments received: ['yolo', 'detect', 'test', 'data=/home/piai/project_yolo/ultralytics/poskick_helmet_5/data.yaml', 'model=yolov8n.pt', 'epochs=150', 'imgsz=640', 'lr0=0.01', 'device=0']. Ultralytics 'yolo' commands use the following syntax:

        yolo TASK MODE ARGS

        Where   TASK (optional) is one of ('detect', 'segment', 'classify', 'pose')
                MODE (required) is one of ('train', 'val', 'predict', 'export', 'track', 'benchmark')
                ARGS (optional) are any number of custom 'arg=value' pairs like 'imgsz=320' that override defaults.
                    See all ARGS at https://docs.ultralytics.com/usage/cfg or with 'yolo cfg'

    1. Train a detection model for 10 epochs with an initial learning_rate of 0.01
        yolo train data=coco128.yaml model=yolov8n.pt epochs=10 lr0=0.01

    2. Predict a YouTube video using a pretrained segmentation model at image size 320:
        yolo predict model=yolov8n-seg.pt source='https://youtu.be/LNwODJXcvt4' imgsz=320

    3. Val a pretrained detection model at batch-size 1 and image size 640:
        yolo val model=yolov8n.pt data=coco128.yaml batch=1 imgsz=640

    4. Export a YOLOv8n classification model to ONNX format at image size 224 by 128 (no TASK required)
        yolo export model=yolov8n-cls.pt format=onnx imgsz=224,128

    5. Run special commands:
        yolo help
        yolo checks
        yolo version
        yolo settings
        yolo copy-cfg
        yolo cfg

    Docs: https://docs.ultralytics.com
    Community: https://community.ultralytics.com
    GitHub: https://github.com/ultralytics/ultralytics

In [ ]:
!pwd

/home/piai/project_yolo/ultralytics

In [ ]:
!yolo predict source=/home/piai/바탕화면/helmetest.jpg save_txt model=/home/piai/project_yolo/ultralytics/runs/detect/train12/weights/best.pt

Ultralytics YOLOv8.0.196 🚀 Python-3.10.13 torch-2.0.1+cu117 CUDA:0 (NVIDIA GeForce RTX 2080, 7974MiB)
Model summary (fused): 168 layers, 3005843 parameters, 0 gradients, 8.1 GFLOPs

image 1/1 /home/piai/바탕화면/helmetest.jpg: 640x352 1 helmet, 47.4ms
Speed: 2.5ms preprocess, 47.4ms inference, 1.8ms postprocess per image at shape (1, 3, 640, 352)
Results saved to runs/detect/predict6
1 label saved to runs/detect/predict6/labels
💡 Learn more at https://docs.ultralytics.com/modes/predict

In [ ]:
!yolo predict source=/content/drive/MyDrive/Colab_Notebooks/helmet.jpg save_txt model=/content/drive/MyDrive/Colab_Notebooks/ultralytics/runs/detect/train2/weights/best.pt

Traceback (most recent call last):
  File "/home/piai/yes/bin/yolo", line 5, in <module>
    from ultralytics.cfg import entrypoint
  File "/home/piai/yes/lib/python3.10/site-packages/ultralytics/__init__.py", line 5, in <module>
    from ultralytics.models import RTDETR, SAM, YOLO
  File "/home/piai/yes/lib/python3.10/site-packages/ultralytics/models/__init__.py", line 3, in <module>
    from .rtdetr import RTDETR
  File "/home/piai/yes/lib/python3.10/site-packages/ultralytics/models/rtdetr/__init__.py", line 3, in <module>
    from .model import RTDETR
  File "/home/piai/yes/lib/python3.10/site-packages/ultralytics/models/rtdetr/model.py", line 3, in <module>
    from ultralytics.engine.model import Model
  File "/home/piai/yes/lib/python3.10/site-packages/ultralytics/engine/model.py", line 9, in <module>
    from ultralytics.hub.utils import HUB_WEB_ROOT
  File "/home/piai/yes/lib/python3.10/site-packages/ultralytics/hub/__init__.py", line 5, in <module>
    from ultralytics.data.utils import HUBDatasetStats
  File "/home/piai/yes/lib/python3.10/site-packages/ultralytics/data/__init__.py", line 4, in <module>
    from .build import build_dataloader, build_yolo_dataset, load_inference_source
  File "/home/piai/yes/lib/python3.10/site-packages/ultralytics/data/build.py", line 18, in <module>
    from .dataset import YOLODataset
  File "/home/piai/yes/lib/python3.10/site-packages/ultralytics/data/dataset.py", line 195, in <module>
    class ClassificationDataset(torchvision.datasets.ImageFolder):
AttributeError: module 'torchvision' has no attribute 'datasets'